import {
  MapPin, Buildings, GenderIntersex, Money,
  WifiHigh, Bed, Shower, Toilet, Television,
  Car, Motorcycle, Key, Wind, Drop, Lightning, Broom,
  Desk, Chair, WashingMachine, FirstAid,
  Fan, Thermometer, ForkKnife, Lamp, Plant, Cat, Dog, Tree,
  Couch, Stairs, SecurityCamera, CoatHanger, Door, GenderFemale, GenderMale, Train, TrainSimple, Hospital, Bathtub, Lockers, ShieldCheck
} from "@phosphor-icons/react";
import type { ComponentType } from "react";

// Explicitly map Phosphor icons to minimize bundle size.
// Only add icons here that are actually used in the database.
export const iconMap: Record<string, ComponentType<any>> = {
  MapPin,
  Buildings,
  GenderIntersex,
  Money,
  WifiHigh,
  Bed,
  Shower,
  Toilet,
  Television,
  Car,
  Motorcycle,
  Key,
  Wind,
  Drop,
  Lightning,
  Broom,
  Desk,
  Chair,
  WashingMachine,
  SecurityCamera,
  FirstAid,
  Fan,
  Thermometer,
  ForkKnife,
  Lamp,
  Plant,
  Cat,
  Dog,
  Tree,
  Couch,
  Stairs,
  CoatHanger,
  Door,
  GenderFemale,
  GenderMale,
  Train,
  TrainSimple,
  Hospital,
  Bathtub,
  Lockers,
  ShieldCheck
};
